### ISSUE TITLE
功能请求：添加 h264_nvenc、hevc_nvenc 编码支持及更多封装格式支持

### ISSUE THREAD

**Issue by Tryanks** [jiayuqi7813/VideoSlimmer#1]
### 描述

首先，我想对您在这个视频转码器上的卓越工作表示感谢。这个工具对许多用户，包括我自己来说，都是非常有价值的。

在使用转码器过程中，我注意到目前它只支持 `av1_nvenc` 编码。为了满足更多的使用场景，增加对 `h264_nvenc` 和 `hevc_nvenc` 导出格式的支持将是非常有帮助的。这些编码格式被广泛使用，添加它们将显著提升该工具的灵活性和实用性。

另外，扩展对更多封装格式（如 `mp4`、`mov`、`mkv`、`flv` 等等）的支持将使这个工具更加多功能和有价值。

### 解决方案建议

1. **添加对 `h264_nvenc` 和 `hevc_nvenc` 的支持**：
   - 实现对 `h264_nvenc` 和 `hevc_nvenc` 的编码选项。
   - 提供如何使用这些新格式的文档和示例。

2. **添加更多封装格式的支持**：
   - 包含如 `mp4`、`mov`、`mkv`、`flv` 等封装格式的支持。
   - 更新文档以反映新的封装格式选项。

### 结论

感谢您考虑这个功能请求。我相信，添加这些编码格式和封装格式的支持将使转码器更加强大和实用，能够满足更广泛用户和应用的需求。您的辛勤工作和奉献精神值得赞赏，我期待看到这个出色工具的持续发展。

**Comment by jiayuqi7813** [comment]
已添加，感谢你的支持
